package entity;
// Generated 2018-05-28 13:03:12 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER"
    ,schema="CZITELS"
)
public class Customer  implements java.io.Serializable {


     private long customerId;
     private Discount discount;
     private Fine fine;
     private String customerName;
     private String customerSurname;
     private String address;
     private String nationality;
     private String documentId;
     private String email;

    public Customer() {
    }

	
    public Customer(long customerId, String customerName, String customerSurname, String address, String nationality, String documentId, String email) {
        this.customerId = customerId;
        this.customerName = customerName;
        this.customerSurname = customerSurname;
        this.address = address;
        this.nationality = nationality;
        this.documentId = documentId;
        this.email = email;
    }
    public Customer(long customerId, Discount discount, Fine fine, String customerName, String customerSurname, String address, String nationality, String documentId, String email) {
       this.customerId = customerId;
       this.discount = discount;
       this.fine = fine;
       this.customerName = customerName;
       this.customerSurname = customerSurname;
       this.address = address;
       this.nationality = nationality;
       this.documentId = documentId;
       this.email = email;
    }
   
     @Id 

    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DISCOUNT")
    public Discount getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FINE")
    public Fine getFine() {
        return this.fine;
    }
    
    public void setFine(Fine fine) {
        this.fine = fine;
    }

    
    @Column(name="CUSTOMER_NAME", nullable=false, length=50)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="CUSTOMER_SURNAME", nullable=false, length=50)
    public String getCustomerSurname() {
        return this.customerSurname;
    }
    
    public void setCustomerSurname(String customerSurname) {
        this.customerSurname = customerSurname;
    }

    
    @Column(name="ADDRESS", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="NATIONALITY", nullable=false, length=50)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="DOCUMENT_ID", nullable=false, length=50)
    public String getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


