package entity;
// Generated 2018-05-28 13:03:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name="DISCOUNT"
    ,schema="CZITELS"
)
public class Discount  implements java.io.Serializable {


     private long discount;
     private String name;
     private long ammount;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public Discount() {
    }

	
    public Discount(long discount, String name, long ammount) {
        this.discount = discount;
        this.name = name;
        this.ammount = ammount;
    }
    public Discount(long discount, String name, long ammount, Set<Customer> customers) {
       this.discount = discount;
       this.name = name;
       this.ammount = ammount;
       this.customers = customers;
    }
   
     @Id 

    
    @Column(name="DISCOUNT", unique=true, nullable=false, precision=10, scale=0)
    public long getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(long discount) {
        this.discount = discount;
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="AMMOUNT", nullable=false, precision=10, scale=0)
    public long getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(long ammount) {
        this.ammount = ammount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discount")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


