package entity;
// Generated 2018-05-28 13:03:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fine generated by hbm2java
 */
@Entity
@Table(name="FINE"
    ,schema="CZITELS"
)
public class Fine  implements java.io.Serializable {


     private long fine;
     private String offense;
     private long penalty;
     private long offenseDate;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public Fine() {
    }

	
    public Fine(long fine, String offense, long penalty, long offenseDate) {
        this.fine = fine;
        this.offense = offense;
        this.penalty = penalty;
        this.offenseDate = offenseDate;
    }
    public Fine(long fine, String offense, long penalty, long offenseDate, Set<Customer> customers) {
       this.fine = fine;
       this.offense = offense;
       this.penalty = penalty;
       this.offenseDate = offenseDate;
       this.customers = customers;
    }
   
     @Id 

    
    @Column(name="FINE", unique=true, nullable=false, precision=10, scale=0)
    public long getFine() {
        return this.fine;
    }
    
    public void setFine(long fine) {
        this.fine = fine;
    }

    
    @Column(name="OFFENSE", nullable=false, length=50)
    public String getOffense() {
        return this.offense;
    }
    
    public void setOffense(String offense) {
        this.offense = offense;
    }

    
    @Column(name="PENALTY", nullable=false, precision=10, scale=0)
    public long getPenalty() {
        return this.penalty;
    }
    
    public void setPenalty(long penalty) {
        this.penalty = penalty;
    }

    
    @Column(name="OFFENSE_DATE", nullable=false, precision=10, scale=0)
    public long getOffenseDate() {
        return this.offenseDate;
    }
    
    public void setOffenseDate(long offenseDate) {
        this.offenseDate = offenseDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fine")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


